/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.espens.asteroids;

import org.slf4j.LoggerFactory;
import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;

import java.net.URI;
import java.net.URISyntaxException;

public class App {

    public static void main(String[] args) throws URISyntaxException {
        System.setProperty("org.slf4j.simpleLogger.logFile", "System.out");
        URI listeningUri = new URI("http://localhost:8000");
        GrizzlyHttpServerFactory.createHttpServer(
                listeningUri,
                new AsteroidsJerseyApplication(),
                true);
        LoggerFactory.getLogger(App.class).info("Started http server on {}", listeningUri);
    }
}
